name: Daily Email Automation

on:
  schedule:
    - cron: '0 8 * * *' # Runs at 8:00 AM UTC every day
  workflow_dispatch: # Lets you run it manually with a button click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          URL_PAGE: ${{ secrets.URL_PAGE }}
        run: python EmailWorkFlow_2.py

